---
sudo: required
services:
  - docker
language: python
cache:
  directories:
    - /home/travis/docker/
env:
  global:
    - DOCKER_CACHE_FILE=/home/travis/docker/cache.tar.gz
before_install:
  - docker --version
  - if [ -f ${DOCKER_CACHE_FILE} ]; then gunzip -c ${DOCKER_CACHE_FILE} | docker load; fi
script:
  - ./build.sh
  - if [[ ${TRAVIS_BRANCH} == "master" ]] || [[ ${TRAVIS_TAG} ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then mkdir -p $(dirname ${DOCKER_CACHE_FILE}) ; docker save $(docker history -q ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} | grep -v '<missing>') | gzip > ${DOCKER_CACHE_FILE}; fi
deploy:
  provider: releases
  api_key: "TOKEN"
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
